import React, { useState } from 'react';
import { View, Text, TouchableOpacity, Modal, StyleSheet } from 'react-native';

export default function HomeScreen({ navigation }) {
  const [modalVisible, setModalVisible] = useState(false);

    return (
        <View style={styles.container}>
              <Text style={styles.title}>My Workspaces</Text>
                    
                          <TouchableOpacity style={styles.fab} onPress={() => setModalVisible(true)}>
                                  <Text style={styles.fabIcon}>+</Text>
                                        </TouchableOpacity>

                                              <Modal visible={modalVisible} transparent animationType="fade">
                                                      <View style={styles.modalBg}>
                                                                <View style={styles.modalContent}>
                                                                            <Text style={styles.modalTitle}>Choose Scan Mode</Text>
                                                                                        
                                                                                                    <TouchableOpacity 
                                                                                                                  style={styles.optionBtn}
                                                                                                                                onPress={() => {
                                                                                                                                                setModalVisible(false);
                                                                                                                                                                navigation.navigate('Scanner', { mode: 'photo_scan' });
                                                                                                                                                                              }}>
                                                                                                                                                                                            <Text style={styles.optionText}>📸 Photo Scan (.glb)</Text>
                                                                                                                                                                                                        </TouchableOpacity>

                                                                                                                                                                                                                    <TouchableOpacity 
                                                                                                                                                                                                                                  style={styles.optionBtn}
                                                                                                                                                                                                                                                onPress={() => {
                                                                                                                                                                                                                                                                setModalVisible(false);
                                                                                                                                                                                                                                                                                navigation.navigate('Scanner', { mode: '3dgs' });
                                                                                                                                                                                                                                                                                              }}>
                                                                                                                                                                                                                                                                                                            <Text style={styles.optionText}>✨ 3D Gaussian Splatting (.ply)</Text>
                                                                                                                                                                                                                                                                                                                        </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                <TouchableOpacity onPress={() => setModalVisible(false)} style={styles.cancelBtn}>
                                                                                                                                                                                                                                                                                                                                                              <Text style={styles.cancelText}>Cancel</Text>
                                                                                                                                                                                                                                                                                                                                                                          </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                    </View>
                                                                                                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                                                                                                  </Modal>
                                                                                                                                                                                                                                                                                                                                                                                                      </View>
                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                        const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                          container: { flex: 1, padding: 20, backgroundColor: '#f5f5f5' },
                                                                                                                                                                                                                                                                                                                                                                                                            title: { fontSize: 24, fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                              fab: { position: 'absolute', bottom: 30, right: 30, width: 60, height: 60, borderRadius: 30, backgroundColor: '#007AFF', justifyContent: 'center', alignItems: 'center', elevation: 5 },
                                                                                                                                                                                                                                                                                                                                                                                                                fabIcon: { color: '#fff', fontSize: 30 },
                                                                                                                                                                                                                                                                                                                                                                                                                  modalBg: { flex: 1, justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.5)' },
                                                                                                                                                                                                                                                                                                                                                                                                                    modalContent: { backgroundColor: '#fff', margin: 20, padding: 20, borderRadius: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                      modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 15 },
                                                                                                                                                                                                                                                                                                                                                                                                                        optionBtn: { padding: 15, backgroundColor: '#f0f0f0', borderRadius: 8, marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                          optionText: { fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                            cancelBtn: { marginTop: 10, alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                              cancelText: { color: 'red', fontSize: 16 }
                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                              