import React, { useState, useRef } from 'react';
import { View, Text, TouchableOpacity, Modal, StyleSheet, ScrollView, Alert } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as Clipboard from 'expo-clipboard';
import JSZip from 'jszip';

const MASTER_COLAB_SCRIPT = `# ==============================================================================
# MASTER 3D SCANNER SCRIPT
# Run this cell in Google Colab (Ensure T4 GPU is enabled in Runtime > Change runtime type)
# ==============================================================================
import os
from google.colab import files

print("=========================================")
print("  AR SCANNER: 3D RECONSTRUCTION PIPELINE ")
print("=========================================")
print("\\n[Step 1] Upload your scan_project.zip file from the app:")
uploaded = files.upload()
zip_name = list(uploaded.keys())[0]

scan_type = input("\\nWhich mode did you scan in? (Enter '1' for Photo Scan / .glb, '2' for 3DGS / .ply): ")

print("\\n[Step 2] Unzipping images...")
!rm -rf dataset && mkdir dataset
!unzip -q "{zip_name}" -d dataset/

print("\\n[Step 3] Installing System Dependencies (COLMAP)...")
!sudo apt-get install -y colmap > /dev/null 2>&1

if scan_type == '2':
    print("\\n[Step 4] Setting up 3D Gaussian Splatting...")
        !git clone https://github.com/graphdeco-inria/gaussian-splatting --recursive
            !pip install -q plyfile
                
                    print("\\n[Step 5] Extracting Camera Poses (This may take a few minutes)...")
                        !python gaussian-splatting/convert.py -s dataset/
                            
                                print("\\n[Step 6] Training Gaussian Splatting...")
                                    !python gaussian-splatting/train.py -s dataset/ -m output_3dgs --iterations 7000
                                        
                                            print("\\n✅ Done! Downloading your 3DGS .ply file...")
                                                files.download('output_3dgs/point_cloud/iteration_7000/point_cloud.ply')

                                                elif scan_type == '1':
                                                    print("\\n[Step 4] Setting up Photogrammetry (Mesh) Pipeline...")
                                                        !pip install -q trimesh
                                                            
                                                                print("\\n[Step 5] Processing images into Mesh...")
                                                                    !colmap automatic_reconstructor --workspace_path dataset/ --image_path dataset/
                                                                        
                                                                            print("\\n[Step 6] Converting to 3D Model...")
                                                                                !colmap model_converter --input_path dataset/sparse/0 --output_path dataset/model.ply --output_type PLY
                                                                                    
                                                                                        import trimesh
                                                                                            mesh = trimesh.load('dataset/model.ply')
                                                                                                mesh.export('dataset/model.glb')
                                                                                                    
                                                                                                        print("\\n✅ Done! Downloading your .glb file...")
                                                                                                            files.download('dataset/model.glb')
                                                                                                            else:
                                                                                                                print("Invalid selection. Please run the cell again.")
                                                                                                                `;

                                                                                                                const MAX_PHOTOS = 700;

                                                                                                                export default function ScannerScreen({ route, navigation }) {
                                                                                                                  const { mode } = route.params;
                                                                                                                    const [permission, requestPermission] = useCameraPermissions();
                                                                                                                      
                                                                                                                        const [photos, setPhotos] = useState([]);
                                                                                                                          const [exportModalVisible, setExportModalVisible] = useState(false);
                                                                                                                            const [isZipping, setIsZipping] = useState(false);
                                                                                                                              
                                                                                                                                const cameraRef = useRef(null);

                                                                                                                                  if (!permission) return <View />;
                                                                                                                                    if (!permission.granted) {
                                                                                                                                        return (
                                                                                                                                              <View style={styles.center}>
                                                                                                                                                      <Text>Camera permission is required to scan.</Text>
                                                                                                                                                              <TouchableOpacity style={styles.btn} onPress={requestPermission}>
                                                                                                                                                                        <Text style={{color: '#fff'}}>Grant</Text>
                                                                                                                                                                                </TouchableOpacity>
                                                                                                                                                                                      </View>
                                                                                                                                                                                          );
                                                                                                                                                                                            }

                                                                                                                                                                                              const takePicture = async () => {
                                                                                                                                                                                                  if (photos.length >= MAX_PHOTOS) {
                                                                                                                                                                                                        Alert.alert("Limit Reached", "You have reached the 700 photo limit.");
                                                                                                                                                                                                              return;
                                                                                                                                                                                                                  }
                                                                                                                                                                                                                      if (cameraRef.current) {
                                                                                                                                                                                                                            const photo = await cameraRef.current.takePictureAsync({ quality: 0.5 });
                                                                                                                                                                                                                                  if (photo?.uri) setPhotos(prev => [...prev, photo.uri]);
                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                          const generateZip = async () => {
                                                                                                                                                                                                                                              if (photos.length === 0) return Alert.alert("No Photos", "Take some photos first.");
                                                                                                                                                                                                                                                  setIsZipping(true);
                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                            const zip = new JSZip();
                                                                                                                                                                                                                                                                  for (let i = 0; i < photos.length; i++) {
                                                                                                                                                                                                                                                                          const base64 = await FileSystem.readAsStringAsync(photos[i], { encoding: FileSystem.EncodingType.Base64 });
                                                                                                                                                                                                                                                                                  zip.file(`scan_${i}.jpg`, base64, { base64: true });
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                    const zipContent = await zip.generateAsync({ type: 'base64' });
                                                                                                                                                                                                                                                                                                          const zipPath = `${FileSystem.documentDirectory}scan_project.zip`;
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                      await FileSystem.writeAsStringAsync(zipPath, zipContent, { encoding: FileSystem.EncodingType.Base64 });
                                                                                                                                                                                                                                                                                                                            await Sharing.shareAsync(zipPath);
                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                      Alert.alert("Error", "Failed to create ZIP");
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                              setIsZipping(false);
                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                  const copyScriptToClipboard = async () => {
                                                                                                                                                                                                                                                                                                                                                      await Clipboard.setStringAsync(MASTER_COLAB_SCRIPT);
                                                                                                                                                                                                                                                                                                                                                          Alert.alert("Copied!", "Script copied to clipboard.");
                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                  <View style={{ flex: 1 }}>
                                                                                                                                                                                                                                                                                                                                                                        <CameraView style={{ flex: 1 }} ref={cameraRef} facing="back" />
                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                    <View style={styles.overlay}>
                                                                                                                                                                                                                                                                                                                                                                                            <Text style={styles.counter}>{photos.length} / {MAX_PHOTOS}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                    <TouchableOpacity style={styles.captureBtn} onPress={takePicture} />
                                                                                                                                                                                                                                                                                                                                                                                                            <TouchableOpacity style={styles.exportBtn} onPress={() => setExportModalVisible(true)}>
                                                                                                                                                                                                                                                                                                                                                                                                                      <Text style={{color: '#fff', fontWeight: 'bold'}}>Export</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                              </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </View>

                                                                                                                                                                                                                                                                                                                                                                                                                                          <Modal visible={exportModalVisible} animationType="slide" presentationStyle="pageSheet">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <View style={styles.modalContent}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Text style={styles.modalTitle}>Export {mode === '3dgs' ? '3DGS' : 'Photo Scan'}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Text style={styles.stepTitle}>1. Download your Images</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <TouchableOpacity style={styles.btn} onPress={generateZip} disabled={isZipping}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Text style={{color: '#fff', textAlign: 'center', fontWeight: 'bold', fontSize: 16}}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {isZipping ? 'Compressing... Please wait' : '📦 Save Project as .ZIP'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </TouchableOpacity>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <View style={styles.scriptHeader}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Text style={styles.stepTitle}>2. Google Colab Script</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <TouchableOpacity style={styles.copyBtn} onPress={copyScriptToClipboard}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Text style={{color: '#fff', fontWeight: 'bold'}}>📋 Copy</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ScrollView style={styles.scriptBox}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Text style={styles.scriptText}>{MASTER_COLAB_SCRIPT}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ScrollView>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <TouchableOpacity style={styles.closeBtn} onPress={() => setExportModalVisible(false)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Text style={{color: '#007AFF', fontSize: 18, fontWeight: 'bold'}}>Close</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Modal>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  overlay: { position: 'absolute', bottom: 40, width: '100%', flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    counter: { color: 'white', backgroundColor: 'rgba(0,0,0,0.5)', padding: 10, borderRadius: 10, overflow: 'hidden', fontWeight: 'bold' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      captureBtn: { width: 70, height: 70, backgroundColor: 'white', borderRadius: 35, borderWidth: 5, borderColor: '#ddd' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        exportBtn: { backgroundColor: '#007AFF', padding: 15, borderRadius: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          modalContent: { flex: 1, padding: 25, marginTop: 40 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            modalTitle: { fontSize: 24, fontWeight: 'bold', marginBottom: 25, textAlign: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              stepTitle: { fontSize: 18, fontWeight: '600', marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                btn: { backgroundColor: '#34C759', padding: 18, borderRadius: 10, marginBottom: 25 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  scriptHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    copyBtn: { backgroundColor: '#007AFF', paddingVertical: 8, paddingHorizontal: 15, borderRadius: 8, marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      scriptBox: { backgroundColor: '#1e1e1e', padding: 15, borderRadius: 10, flex: 1, marginBottom: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        scriptText: { color: '#00ff00', fontFamily: 'monospace', fontSize: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          closeBtn: { padding: 15, alignItems: 'center', marginBottom: 20 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          